language: swift
osx_image: xcode9.3
xcode_project: GlassNavigationBar.xcodeproj
xcode_scheme: GlassNavigationBar
xcode_sdk: iphonesimulator11.3
sudo: required

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update
  - pod repo update
  
script:
  - set -o pipefail
  - git submodule update --init
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project GlassNavigationBarExample.xcworkspace -target GlassNavigationBar -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
